# Generated by Django 2.1.4 on 2019-01-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190105_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspoint',
            name='device_lat',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gpspoint',
            name='device_long',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='device_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
