# Generated by Django 2.1.4 on 2019-01-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190105_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.CharField(choices=[('Ab', 'Abgeschlossen'), ('Ge', 'Geoeffnet')], max_length=3),
        ),
    ]
