# Generated by Django 2.1.3 on 2019-01-09 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190109_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 9, 13, 50, 58, 507536)),
        ),
        migrations.AlterField(
            model_name='gpspoint',
            name='record_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 9, 13, 50, 58, 507536)),
        ),
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 9, 13, 50, 58, 507536)),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 9, 13, 50, 58, 507536)),
        ),
    ]
