# Generated by Django 2.1.3 on 2019-01-09 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190109_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpspoint',
            name='route',
        ),
        migrations.RemoveField(
            model_name='route',
            name='tracker',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='device_lat',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='device_long',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='last_update',
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='device_alt',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='tracker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Tracker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpspoint',
            name='record_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 9, 21, 35, 38, 848676)),
        ),
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 9, 21, 35, 38, 848676)),
        ),
    ]
