# Generated by Django 2.1.3 on 2019-01-10 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190109_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspoint',
            name='record_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 20, 33, 9, 95289)),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 10, 20, 33, 9, 94197)),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.CharField(choices=[('Ab', 'Abgeschlossen'), ('Ge', 'Geoeffnet'), ('Ra', 'Route aufzeichnen')], max_length=3),
        ),
    ]
