# Generated by Django 2.1.3 on 2019-01-15 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190110_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='tracker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Tracker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpspoint',
            name='record_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 15, 12, 25, 12, 179339)),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 15, 12, 25, 12, 178340)),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='status',
            field=models.CharField(choices=[('Ab', 'Abgeschlossen'), ('Ge', 'Geöffnet'), ('Ra', 'Route aufzeichnen')], max_length=3),
        ),
    ]
