# Generated by Django 2.1.3 on 2019-01-18 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190118_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 18, 13, 35, 54, 760416)),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='device_eui',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='device_name',
            field=models.CharField(max_length=50),
        ),
    ]
