# Generated by Django 2.1.3 on 2019-01-18 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190118_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspoint',
            name='device_lat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gpspoint',
            name='device_long',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gpspoint',
            name='record_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 18, 13, 44, 59, 332037)),
        ),
    ]
