# Generated by Django 2.1.3 on 2019-01-31 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190118_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='connect_status',
            field=models.CharField(choices=[('Off', 'Verbindung unterbochen'), ('On', 'Verbindung aktiv'), ('GPS', 'GPS Funkloch')], default='Off', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 31, 18, 39, 0, 347649)),
        ),
    ]
